### ISSUE TITLE
包缺失

### ISSUE THREAD

**Issue by saemoo** [panda726548/yiran#1]
你好，请问netfinworks-common-lang这个包是私有的吗，一直找不到。

**Comment by panda726548** [comment]
<dependency>
		<groupId>com.netfinworks.common</groupId>
		<artifactId>netfinworks-common-lang</artifactId>
		<version>1.0</version>
	</dependency>

**Comment by panda726548** [comment]
试试这个
<dependency>
		<groupId>com.netfinworks.common</groupId>
		<artifactId>netfinworks-common-lang</artifactId>
		<version>1.0</version>
	</dependency>
[1.0.zip](https://github.com/panda726548/yiran/files/3844108/1.0.zip)

**Comment by panda726548** [comment]
```
<dependency>
		<groupId>com.netfinworks.common</groupId>
		<artifactId>netfinworks-common-lang</artifactId>
		<version>1.0</version>
	</dependency>
```
